### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by dero2k** [ashleykleynhans/raid-scanner#1]
Hi

i always get this error

22:44:37 - debug: Import gyms from gyms.csv
22:44:37 - info: Scanning gym at 49.23339, 7.013273
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request.request.get [as _callback] (/Users/macair/2/raid-scanner/node_modules/pogobuf-signature/versions.js:22:39)
    at Request.self.callback (/Users/macair/2/raid-scanner/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/macair/2/raid-scanner/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/macair/2/raid-scanner/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by ashleykleynhans** [comment]
Hashing service is down.
